name: build-html

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout-code
      
    - name: build-image
      run: |
        docker build -t appstellaracademy/html:latest .
      working-directory: html

    - name: docker-login
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PAT }}
      
    - name: publish
      run: |
        docker push appstellaracademy/html:latest
  
