name: validate-build-html

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      name: checkout-code
      
    - name: build-image
      run: |
        docker build -t docker-labs/html:latest .
      working-directory: html
